name: 不实信息举报
description: 举报平台上的不实信息
title: "[举报] 不实信息 - 公司名称"
labels: ["type:false-report", "status:pending"]
body:
  - type: input
    id: company-id
    attributes:
      label: 公司ID
      description: 请填写被举报内容的公司ID（可在详情页URL中找到）
      placeholder: 如：1001
    validations:
      required: true

  - type: input
    id: company-name
    attributes:
      label: 公司名称
      description: 请填写被举报内容涉及的公司名称
      placeholder: 如：xx科技（xx）有限公司
    validations:
      required: true

  - type: textarea
    id: false-content
    attributes:
      label: 不实内容描述
      description: 请详细描述您认为不实的内容
      placeholder: 请详细描述不实内容...
    validations:
      required: true

  - type: textarea
    id: evidence
    attributes:
      label: 证明材料
      description: 请提供能够证明该信息不实的材料
      placeholder: 请提供证明材料...
    validations:
      required: true

  - type: input
    id: contact
    attributes:
      label: 联系方式
      description: 请提供您的联系方式，以便我们与您联系
      placeholder: 如：email@example.com
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: 声明与承诺
      description: 请确认以下内容
      options:
        - label: 我保证所提供的信息真实可靠
          required: true
        - label: 我已阅读并同意项目的《免责声明》
          required: true
