name: 企业避雷爆料
description: 提交企业违规行为爆料
title: "[爆料] 公司名称 - 城市"
labels: ["status:pending"]
body:
  - type: input
    id: company-name
    attributes:
      label: 公司全称
      description: 请填写完整的公司名称
      placeholder: 如：xx科技（xx）有限公司
    validations:
      required: true

  - type: input
    id: city
    attributes:
      label: 所在城市
      description: 请填写公司所在城市
      placeholder: 如：深圳
    validations:
      required: true

  - type: checkboxes
    id: tags
    attributes:
      label: 问题标签
      description: 请选择适用的标签（可多选）
      options:
        - label: "强制加班（996/007/其他？）"
        - label: "拖欠工资/奖金"
        - label: "裁员不赔偿"
        - label: "职场PUA/精神压迫"
        - label: "社保公积金违规"
        - label: "试用期违规"
        - label: "职场歧视（性别/年龄/地域等）"
        - label: "虚假招聘"
        - label: "竞业协议违规"
        - label: "强迫辞职"
        - label: "不提供离职证明"
        - label: "劳动保护缺失"
        - label: "培训费用陷阱"
        - label: "其他问题"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 详细描述
      description: 请详细描述您遇到的问题，包括时间、地点、具体事件等
      placeholder: 请尽可能详细地描述...
    validations:
      required: true

  - type: textarea
    id: evidence
    attributes:
      label: 证据材料
      description: 请提供相关证据，如截图、聊天记录、邮件等（可附链接）
      placeholder: 请提供证据...

  - type: checkboxes
    id: terms
    attributes:
      label: 声明与承诺
      description: 请确认以下内容
      options:
        - label: 我保证所提供的信息真实可靠
          required: true
        - label: 我同意公开我的 GitHub 用户名（用于身份验证）
          required: true
        - label: 我已阅读并同意项目的《免责声明》
          required: true
