name: 参与审核申请
description: 申请成为平台的审核员
title: "[申请] 我想成为审核员 - 用户名"
labels: ["type:reviewer-application", "status:pending"]
body:
  - type: input
    id: username
    attributes:
      label: GitHub 用户名
      description: 请填写您的 GitHub 用户名
    validations:
      required: true

  - type: textarea
    id: experience
    attributes:
      label: 审核相关经验
      description: 请描述您的审核相关经验，包括但不限于内容审核、社区管理等
      placeholder: 请详细描述您的审核经验...
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: 申请动机
      description: 请说明您想成为审核员的原因和动机
      placeholder: 请说明您的申请动机...
    validations:
      required: true

  - type: input
    id: contact
    attributes:
      label: 联系方式
      description: 请提供您的联系方式
      placeholder: 如：email@example.com
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: 声明与承诺
      description: 请确认以下内容
      options:
        - label: 我保证所提供的信息真实可靠
          required: true
        - label: 我同意遵守平台的审核规则和行为准则
          required: true
        - label: 我承诺公正、客观地进行审核工作
          required: true
        - label: 我已阅读并同意项目的《免责声明》
          required: true
